<Discount>
1.0
</Discount>

<IcedReward>
0.0
</IcedReward>

<GoalReward>
1.0
</GoalReward>

<Start>
0.15 0.15 0.0
</Start>

<Goal>
0.85 0.85 0.0
</Goal>

<Obstacle>
0.46 0.69
1.1 0.69
1.1 0.61
0.46 0.61
</Obstacle>

<Obstacle>
0.56 0.64
1.1 0.64
1.1 0.51
0.56 0.51
</Obstacle>

<Obstacle>
-1.0 0.36
0.44 0.36
0.44 0.49
-1.0 0.49
</Obstacle>

<Obstacle>
-1.0 0.31
0.54 0.31
0.54 0.39
-1.0 0.39
</Obstacle>

<AxisResolution>
20
</AxisResolution>

<OrientationResolution>
16
</OrientationResolution>
