<Start>
0.15 0.15 1.57
</Start>

<Goal>
0.15 0.85 1.57
</Goal>

<Obstacle>
0.11 0.46
0.49 0.46
0.49 0.54
0.11 0.54
</Obstacle>

<Obstacle>
0.81 0.19
1.1 0.19
1.1 -1
0.81 -1
</Obstacle>

<Obstacle>
0.81 0.81
1.0 0.81
1.0 1.0
0.81 1.0
</Obstacle>

<AxisResolution>
20
</AxisResolution>

<OrientationResolution>
16
</OrientationResolution>

<GoalReward>
10000
</GoalReward>

<IcedReward>
100
</IcedReward>
